"""Exports a trained ValueNet checkpoint to a plain-data TypeScript module
that src/lib/valueNet.ts can run with a hand-written forward pass -- no ONNX
runtime / tfjs dependency, since this needs to run unmodified inside the iOS
JSContext (see CLAUDE.md's "written once in src/lib" rule) with nothing
heavier than arithmetic.

    python export_weights.py --checkpoint checkpoints/value_net.pt \
        --out ../src/lib/valueNetWeights.generated.ts
"""
import argparse
import json

import torch

from model import ValueNet


def to_list(t):
    return t.detach().cpu().numpy().tolist()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", default="checkpoints/value_net.pt")
    parser.add_argument("--out", default="../src/lib/valueNetWeights.generated.ts")
    args = parser.parse_args()

    model = ValueNet()
    model.load_state_dict(torch.load(args.checkpoint, map_location="cpu"))
    model.eval()

    sd = model.state_dict()
    weights = {
        "hexW1": to_list(sd["hex_encoder.0.weight"]),
        "hexB1": to_list(sd["hex_encoder.0.bias"]),
        "hexW2": to_list(sd["hex_encoder.2.weight"]),
        "hexB2": to_list(sd["hex_encoder.2.bias"]),
        "headW1": to_list(sd["head.0.weight"]),
        "headB1": to_list(sd["head.0.bias"]),
        "headW2": to_list(sd["head.2.weight"]),
        "headB2": to_list(sd["head.2.bias"]),
    }

    lines = [
        "// Generated by ml/export_weights.py -- do not hand-edit.",
        "// Regenerate after retraining: python ml/export_weights.py",
        "",
    ]
    for name, value in weights.items():
        lines.append(f"export const {name} = {json.dumps(value)} as const;")
    lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
